name: Run Gradle on PRs and Pushes
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        timeout-minutes: 3
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
          cache: gradle

      - name: build
        timeout-minutes: 5
        run: "./gradlew packageUberJarForCurrentOS"
        env:
          _JAVA_OPTIONS: '-Duser.language=ja -Duser.country=JP'

      - name: upload-artifact
        timeout-minutes: 5
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: UberJar-${{ runner.os }}
          path: |
            build/compose/jars/*.jar

      - name: Set current datetime.
        timeout-minutes: 1
        if: ${{ success() }}
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "current_date=$(date + '%Y-%m-%d')" >> $GITHUB_ENV
 
      - name: Update Pull Request Title
        timeout-minutes: 5
        if: ${{ success() }}
        run: |
          echo "tag_title=v0.9.1_${current_date} >> $GITHUB_ENV"
          gh release create ${tag_title} --title ${tag_title} build/compose/jars/*.jar

      - name: Upload Kotlin build report
        timeout-minutes: 2
        uses: actions/upload-artifact@v4
        with:
          name: Kotlin build report-${{ runner.os }}
          path: |
            build/reports/kotlin-build

  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        timeout-minutes: 3
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
          cache: gradle

      - name: kover
        timeout-minutes: 15
        env:
          TZ: 'Asia/Tokyo'
          _JAVA_OPTIONS: '-Duser.language=ja -Duser.country=JP -Duser.timezone=Asia/Tokyo'
        run: "./gradlew koverHtmlReport"

      - name: Upload Unit Test Results
        timeout-minutes: 3
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: |
            build/reports/tests
            domain/build/reports/tests
            infrastructure/build/reports/tests
            presentation/build/reports/tests

      - name: Upload Kover Results
        timeout-minutes: 3
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Kover Results
          path: |
            build/reports/kover

      - name: Upload Kotlin build report
        timeout-minutes: 2
        uses: actions/upload-artifact@v4
        with:
          name: Kotlin build report-test
          path: |
            build/reports/kotlin-build

      - name: Print summary
        timeout-minutes: 1
        if: ${{ success() }}
        run: ./gradlew printCoverageSummary

      - name: Store summary
        timeout-minutes: 1
        if: ${{ success() }}
        run: |
          echo "## Test coverage" >> $GITHUB_STEP_SUMMARY
          ./gradlew printCoverageSummary >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Download Artifacts
        timeout-minutes: 1
        if: ${{ success() }}
        uses: actions/download-artifact@v4
        with:
          path: artifacts
