name: Run Gradle on PRs and Pushes
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: build
        run: "./gradlew packageUberJarForCurrentOS"
        env:
          _JAVA_OPTIONS: '-Duser.language=ja -Duser.country=JP'

      - name: upload-artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: UberJar
          path: |
            build/compose/jars

  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: kover
        env:
          TZ: 'Asia/Tokyo'
          _JAVA_OPTIONS: '-Duser.language=ja -Duser.country=JP -Duser.timezone=Asia/Tokyo'
        run: "./gradlew koverHtmlReport"

      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: |
            build/reports/tests
            domain/build/reports/tests
            infrastructure/build/reports/tests
            presentation/build/reports/tests

      - name: Upload Kover Results
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Kover Results
          path: |
            build/reports/kover

      - name: Print summary
        if: ${{ success() }}
        run: ./gradlew readCoverageSummary >> $GITHUB_STEP_SUMMARY

      - name: Download Artifacts
        if: ${{ success() }}
        uses: actions/download-artifact@v4
        with:
          path: artifacts
