name: Run Gradle on PRs and Pushes
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: build
        with:
          arguments: "./gradlew test packageUberJarForCurrentOS"

  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: kover
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "koverHtmlReport"


